[package]
name = "entry-point"
version = "0.1.0"
authors = ["Brainium Studios LLC"]
edition = "2018"
license = "Apache-2.0/MIT"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.10"
quote = "1.0.3"
syn = { version = "1.0.17", features = ["full"] }
