[package]
name = "entry-point"
version = "0.1.0"
authors = ["Brainium Studios LLC"]
edition = "2018"
license = "Apache-2.0/MIT"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
quote = "0.6"
syn = { version = "0.15", features = ["full"] }
